### ISSUE TITLE
Provide wheel package on PyPI

### ISSUE THREAD

**Issue by edmorley** [mozilla/django-browserid#293] opened 2015-10-30 10:35 UTC
Please could you provide a wheel package on PyPI alongside the standard package? http://pythonwheels.com/

Thanks :-)

**Comment by peterbe** [comment] 2015-10-30 21:24
@Osmose how do you do the releases? If you don't already use it, all you need to do is:
```
$ pip install wheel
$ python setup.py sdist bdist_wheel upload
```
I would recommend that you let travis run this. That's what I do on all my python projects. [For example](https://github.com/peterbe/premailer/blob/master/.travis.yml#L39)

**Comment by Osmose** [comment] 2015-11-02 18:52
I bumped the version and added a setup.cfg file: https://github.com/mozilla/django-browserid/commit/729e1afee6b94381c5fbbd0b4a00d8da4b225bc9

However, when I published to PyPI it marked the universal wheel as Python 2.7: https://pypi.python.org/pypi/django-browserid/1.0.1/

Any ideas as to why this happened?

**Comment by Osmose** [comment] 2015-11-02 18:53
CC @jezdez as he is brilliant and may know why. :D

**Comment by jezdez** [comment] 2015-11-02 18:56
@Osmose Don't worry, that's just PyPI being silly, it shows which platform the upload was from when it can't figure out the version from the file name. pip and wheel will take a look at the filename of the wheel file and find it to be matching both platforms, py2 and py3, so all should be good.

BTW, since @peterbe was referring to using the upload subcommand of setup.py, **please don't use it**. It sends you credentials unencrypted because distutils is stupid. Follow the officially recommended guidelines and use [twine](https://github.com/pypa/twine) instead.

**Comment by jezdez** [comment] 2015-11-02 18:57
OOPS, forgot the link to the docs: https://packaging.python.org/en/latest/distributing/#upload-your-distributions

**Comment by jezdez** [comment] 2015-11-02 18:59
That's what Twine is using since this summer as well, https://github.com/travis-ci/dpl/commit/8b091fa9ee24bc753cbd5aec24b55e60d0bb33f4

**Comment by peterbe** [comment] 2015-11-02 20:09
Wow! That I had no idea about! How disappointing that it does that. 
Ok. So I'll use `python setup.py sdist bdist_wheel` and `twine upload dist/*` instead if I ever do it manually. 

But [is this safe](https://github.com/peterbe/premailer/blob/0ae7a61edd41dfb9296bcc24d137a6e0fbb79b41/.travis.yml#L39-L46)? I know that stopped working at some point until I added [`pip install twine`](https://github.com/peterbe/premailer/blob/0ae7a61edd41dfb9296bcc24d137a6e0fbb79b41/.travis.yml#L17).

**Comment by jezdez** [comment] 2015-11-02 20:11
@peterbe Yeah, that should be safe, https://github.com/travis-ci/dpl/commit/8b091fa9ee24bc753cbd5aec24b55e60d0bb33f4 made Travis install twine in their virtualenv by default, it's odd that it failed for you. Could you open a ticket in the dpl repo in case you can reproduce it?

**Comment by peterbe** [comment] 2015-11-02 20:39
@jezdez I can't reproduce it any more. It was a long time ago. I think the error some simply something like `bash: twine: command not found` at the very bottom of the travisCI output. When it happened I had never heard of `twine` and some quick stackoverflow searches said to simply add `pip install twine` as a prerequisite.

**Comment by edmorley** [comment] 2015-11-02 21:40
That's great - thank you :-)

**Comment by Osmose** [comment] 2015-12-04 00:10
Closing this, since we have a wheel that apparently works. :D

**Closed by Osmose** 2015-12-04 00:10 UTC
